### ISSUE TITLE
[Question] Is there a way to display errors/warnings in 'Problems' tab on VSCode?

### ISSUE THREAD

**Issue by rtxa** [Hedgefog/node-amxxpack#11]
I wonder if it's possible to show the the errors/warnings in `Problems` tab on VSCode. I see that I can't go to the error code line by pressing CTRL while clicking in `836`. Probably is mising the `:` at the beggining which will make it a line search. Not sure if this requires modifications on Klyppy AMXXPawn extension.

![](https://i.imgur.com/QhmLsrz.png)

**Comment by hedgefog** [comment]
Previously this function worked (click by error), but for some reason, VSCode developers changed the format for link detection. I'll fix format in the next update.
I think the only way to add warnings/errors to the Problems tab is to write an extension.

**Comment by rtxa** [comment]
Thanks for looking into this. I did some research and looks like this can be configured with `tasks.json`.

I did a pretty basic one just and it seems to be working, but because I'm running a watch task, old errors would stay in the Problems panel, unless I figured how to tell VSCode to clean old errors if that file is being compiled again. This part of the documentation can be helpful https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks.

Maybe when configuring the project, this can come preinstalled.

This is how it looks like:

![](https://i.imgur.com/PFc8kGk.png)

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"group": "build",
			"isBackground": true,
			"problemMatcher": [
				{
					"owner": "amxxpack",
					"fileLocation": [
						"autoDetect",
						"${workspaceFolder}"
					],
					"pattern": {
						"regexp": "^\\[(ERROR|WARNING)\\] \\s*(.*)\\((\\d*)\\) \\s*(.*)",
						"severity": 1,
						"file": 2,
						"location": 3,
						"message": 4,
					}
				}
			],
			"label": "npm: watch",
			"detail": "amxxpack build --watch"
		}
	]
}
```

**Comment by hedgefog** [comment]
Awesome stuff!

**Comment by rtxa** [comment]
Thanks Hedgefog.

So, in order for VSCode to be able to detect when the watch tasks have been updated and reset previous errors in _Problems_ panel, it need some kind of signal message like it does with gulp with TypeScript internally according to the link I send you before about tasks when running in `--watch` mode.

```
12:32:35 PM - File change detected. Starting incremental compilation...
src/messages.ts(276,9): error TS2304: Cannot find name 'candidate'.
12:32:35 PM - Compilation complete. Watching for file changes.
```

So basically, I think what is missing is the start and end message. The start message `File change detected. Starting incremental compilation... `isn't required when running the task for the first time

Right now, it's looks like this:

```ini
[INFO] Asset updated: C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/scripting/agmodx.sma
[ERROR] valve/addons/amxmodx/scripting/agmodx.sma(905) error 17 : undefined symbol "set_pcvar_nu"
[ERROR] Failed to compile valve/addons/amxmodx/scripting/agmodx.sma : "Compilation error"
```
And I think it should be like this:

```ini
[INFO] File change detected. Starting incremental compilation...
[INFO] Asset updated: C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/scripting/agmodx.sma
[ERROR] valve/addons/amxmodx/scripting/agmodx.sma(905) error 17 : undefined symbol "set_pcvar_nu"
[ERROR] Failed to compile valve/addons/amxmodx/scripting/agmodx.sma : "Compilation error"
[INFO] Compilation complete. Watching for file changes.
```

On success, it would be like this:
```ini
[INFO] File change detected. Starting incremental compilation...
[INFO] Asset updated: C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/scripting/agmodx.sma
[SUCCESS] Script compiled successfully: valve/addons/amxmodx/scripting/agmodx.sma
[INFO] Plugin updated: C:/Users/rtxa/Documents/Servidores HL/AG Mod X/valve/addons/amxmodx/plugins/agmodx.amxx
[INFO] Script updated: C:/Users/rtxa/Documents/GitHub/agmodx/dist/addons/amxmodx/scripting/agmodx.sma
[INFO] Compilation complete. Watching for file changes.
```

Maybe this can be less verbose and requires a little bit more of work, please let me know what you think.

PD: Also I see a good idea to display the timestamp in the message.

**Comment by hedgefog** [comment]
Thanks for your help! Logs improved in version 1.4.0.
