### ISSUE TITLE
Cache files to avoid rebuilding the entire project

### ISSUE THREAD

**Issue by rtxa** [Hedgefog/node-amxxpack#2]
Sometimes when your project has a lot of resources (like models, sounds, maps), the building process will get a slowdown.  
It will be useful to cache the files for the next `amxxpack build` command call to avoid wasting any precious time and save it only for the compiling part.

The command `amxxpack build --watch` help with this issue but the caching is only stored in-memory and not in the disk storage, as soon as you stop the task for some reason, you have to go back to the rebuilding process again.

Maybe this article can help you with this: https://medium.com/@wlarch/avoid-long-running-and-killed-gulp-tasks-with-this-simple-caching-gulp-plugin-67ec8bbf466b

> Do not waste time during your build process when there is no reason to.
>
> This plugin will process all files in gulp.src() if at least one file was changed. This plugin uses the features of [node-file-cache](https://www.npmjs.com/package/node-file-cache) to keep track of the assets SHA1 hashed content in a cache.json file.

**Comment by hedgefog** [comment]
Work in Progress: https://github.com/Hedgefog/node-amxxpack/pull/7
