### ISSUE TITLE
Make the assets configuration more powerful

### ISSUE THREAD

**Issue by rtxa** [Hedgefog/node-amxxpack#4]
Right now the way the assets are copied works fine for simple projects, it will just copy the entire folder. But for more complex projects, it will be useful to have the ability to exclude some folders, to add more folders for copying, maybe the ability to avoid copying sub-dirs inside that dir. Doing this will avoid the necessity to use external scripts.

To put it more clear, these are some of the options I would like to see implemented:
- Exclude folders for copying
- Being able to add more folders for copying
- Have the ability to choose if we need to copy also subdirs
- Limit copying by file extension.

For example, I have my project ([AG Mod X](https://github.com/rtxa/agmodx)) which has assets like maps, models and sprites which are fine for those, but I have too files that are platform dependent like the server binaries (custom DLLs, Metamod, etc.). We need to have the ability to export assets by platform, like having two folders inside `dist`, one for Windows for Linux. Right now this stops me from using AMXXPack to its full potential.

How can this be implemented? I'm not sure, maybe I can give a draft how this will look inside the `.amxxpack.json` if you are interested.

**Comment by hedgefog** [comment]
Work in Progress: https://github.com/Hedgefog/node-amxxpack/pull/7

**Comment by rtxa** [comment]
Good you are on this, I'll test it when it's ready :)

**Comment by hedgefog** [comment]
Added the ability to use multiple directories for src, includes, assets. Using new functionality with various configurations will partially cover the described case.
Check https://github.com/Hedgefog/cs-halloween-mod to see an example of using multiple configurations.

**Comment by hedgefog** [comment]
Use objects with `dir` and `filter` fields for assets input instead of a string. More info: https://github.com/Hedgefog/node-amxxpack#assets-filtering-and-subdirectories
