### ISSUE TITLE
Skip bad plugins when building

### ISSUE THREAD

**Issue by ufame** [Hedgefog/node-amxxpack#5]
The whole assembly breaks off if at least 1 plugin is not approved by the compiler (Compilation aborted...). It is extremely inconvenient when building a large project - I would like to skip such plugins and continue building the following plugins.

**Comment by hedgefog** [comment]
Work in Progress: https://github.com/Hedgefog/node-amxxpack/pull/7

**Comment by hedgefog** [comment]
added `--ignore` build flag
